### ISSUE TITLE
Uses init_x twice in particle_filter_main

### ISSUE THREAD

**Issue by AndrewNolte** [ut-amrl/cs378_starter#2]
I think this is supposed to use init_y
https://github.com/ut-amrl/cs378_starter/blob/master/src/particle_filter/particle_filter_main.cc#:~:text=Vector2f(CONFIG_init_x_%2C%20CONFIG_init_x_)%2C

**Comment by joydeep-b** [comment]
Thanks, Andrew, fixed with [cc2642a](https://github.com/ut-amrl/cs378_starter/commit/cc2642a275005180b615f45fbf28b5ad62b2bc0a)
